### ISSUE TITLE
VMA - files being refetched continuously 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1015]
This behavior is being reported for all vendors related to the [recent FTP issue ](https://github.com/sul-dlss/libsys-airflow/issues/944)(gaiads, leila, coutts). 

I ran GAIADS at 1 yesterday and 
Files fetched:

ST26754.mrc
ST26750.mrc
ST26752.mrc
ST26753.mrc
ST26708.mrc

Then it ran again on the schedule around 5 and 
Files fetched:

ST26754.mrc
ST26750.mrc
ST26752.mrc
ST26753.mrc
ST26708.mrc

**Comment by ahafele** [comment]
@jermnelson I'm testing gaiads in production and this seems to have fixed the re-fetching issue but there is a new problem - fetched files don't seem to get processed. See https://sul-libsys-airflow-prod.stanford.edu/vendor_management/interfaces/43 the file is status of "fetched" and expected processing time was 2024-05-24 15:17:35.208570. I would expect this to have been processed already with the processed file available for download in the UI.

**Comment by ahafele** [comment]
@jermnelson maybe expected processing doesn't mean what I think? I just got an email it was processed.

**Comment by jermnelson** [comment]
@ahafele, the fetching and processing are done in separate DAGs with the `default_data_processing` DAG being triggered by `folio_processing_scheduler` DAG that runs hourly. The expected processing time is based on the when the vendor file is created and any `processing_delay_in_days` so that time isn't related to when the `default_data_processing` DAG is triggered.

**Comment by ahafele** [comment]
Ok, thanks for explaining! This is done then, thank you!
