### ISSUE TITLE
856 Electronic Holdings Record Task

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#102]
Add task to the `bib_records` DAG to generate a FOLIO Holding Records based on values in the MARC records 856 fields. Based on these mapping values contained in https://docs.google.com/spreadsheets/d/1XUSjuysc33NUIJ3SpoYAbTL7_rQojJhGm9KUAlaQD_Q/edit#gid=0, with the following assumptions:

- The last subfield x in the 856 field may contain the Vendor code. This value should be added as a note with a note type of *Vendor* on the holdings record. Each Vendor has a separate FOLIO Electronic Holdings Record
- Remaining subfield x values stored in a Holdings note. 
- Volume information in subfield 3 in the 856 will be stored in the in `electronicAccess.materialsSpecification`

**Comment by ahafele** [comment]
@jermnelson The vendor code will not always be in the last subfield x. But it will always be two letters followed by "4". I think we want to move all subfield x's to a note. Delimited in one note field (to start) but perhaps the vendor id should be in a separate note?

**Comment by jermnelson** [comment]
@ahafele I clarified and update the ticket's description. Do you have a preferred delimiter for the subfield x values in the note field? Thanks!

**Comment by dlrueda** [comment]
Logic needed to assign correct location to the holdings is in Data Migration folder of Implementation drive, in https://docs.google.com/document/d/1j4CvDxMqbA8JxZ9jNqiitiboEDYkQ5W6z_fLIxcLGP4/edit

Briefly:
If 596 includes 24, create holdings for LAW-ELECTRONIC
Else if includes 28, create holdings for BUS-ELECTRONIC
Else if includes 25 or 28, create holdings for HILA-ELECTRONIC
Else create holdings for SUL-ELECTRONIC

This logic will only work for migration, since that 596 is generated by Symphony during indexing.
