### ISSUE TITLE
Adding 979 blank emails

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/libsys-airflow#1392]
Receiving some blank **Summary of Adding 979 fields to MARC** emails. Per Jeremy Maybe when no 979s are added then don’t trigger the polling dag?

**Comment by shelleydoljack** [comment]
It looks like for the task retrieve_variables, if it is a manual run, then we have dag_runs returned and proceed with sending an email. But for the scheduled runs of poll_for_digital_bookplate_979_emails it always returns empty (the list of dag run IDs) yet we send an email. I wonder why there is even a scehdule for this dag since it should always be triggered from the other dag.
