### ISSUE TITLE
Create  example DAG for Gobi [was: Scaffold the Dynamic Vendor Load DAG]

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#268]
Trigged by [Daily monitoring DAG](https://github.com/sul-dlss/libsys-airflow/issues/247), the payload received from Vendor Management App will create a DAG run that will dynamically assemble tasks specific to an Organization's Interface and from additional fields in the payload.

_NOTE_: we've decided to be less dynamic about how we create and run DAGs, and to create vendor specific DAGs, because variation between vendors is greater than we initially expected.  Jeremy is working on getting an example PR up for a single vendor, Gobi, which is the new purpose of this ticket.

**Comment by jmartin-sul** [comment]
helpful diagrams and docs:
* https://github.com/sul-dlss/libsys-airflow/wiki/Data-Loading-Pipeline
* https://docs.google.com/document/d/11JzLJb9kbW4u3dDLZ9_oFtsRtmnPkl0laS4zigQh5X0/edit

**Comment by jmartin-sul** [comment]
What's dynamic about the DAG?  possibly:
* which vendors to run
* which tasks to run for a given vendor (e.g. some or all of invoices, orders, and bib records)

DLME Airflow may provide an in-house reference for this sort of work, since it also does some dynamic DAG building.  @aaron-collier or @edsu may be able to pair on using DLME as an example.

**Comment by jermnelson** [comment]
For this ticket, just create placeholder Tasks using the [EmptyOperator](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/empty/index.html) that can be replaced with  [PythonOperators](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/python/index.html#airflow.operators.python.PythonOperator) once those tickets are implemented.

**Comment by jmartin-sul** [comment]
This ticket will be done when the tasks can be loaded and seen in the Airflow GUI (even if the tasks are `EmptyOperator` placeholders that will later be replaced by `PythonOperator` implementations).  The outline of the DAG, but not the full implementation (because the data loading app endpoints don't exist yet).

**Comment by ndushay** [comment]
I saw something in the running notes implying this was done.  Is it done?  Where do we look to check?

**Comment by lwrubel** [comment]
If I understand correctly, the Daily monitoring DAG is done, but this is a different DAG which is yet to be done. https://github.com/sul-dlss/libsys-airflow/issues/247

It may be that we want to name these differently in the code/UI to make their purpose clearer.

**Comment by ndushay** [comment]
Possibly see https://github.com/sul-dlss/FOLIO-Project-Stanford/wiki/Vendor-Management---FOLIO---Airflow-Interaction-Diagram

Also, we seem to be switching to vendor specific dags ... not sure if that relates directly to this ticket or not.

**Comment by jermnelson** [comment]
@aaron-collier and I will be meeting tomorrow but yes this ticket will be replaced by upcoming vendor-specific DAG tickets. I'll keep this ticket open for now to track the example vendor DAG I'm working on.

**Comment by jermnelson** [comment]
Closing this issue with example Gobi PR closed yesterday.
