### ISSUE TITLE
Handle wrongly encoded MARC Records

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#491]
Our current strategy of reading [MARC records](https://github.com/sul-dlss/libsys-airflow/blob/f1d33d2c748614523e4f13379eb07821381f1dac/libsys_airflow/plugins/vendor/marc.py#L101-L104) from Vendors is to explicitly set the `to_unicode` param to True, the problem is that we have MARC records that encoded as MARC8 but have a value `a` in position 9 in the leader that indicate that the record is UTF-8 This results in records with MARC8 characters that are incorrectly encoded as UTF-8. 

For example, this a record contains Korean MARC8 characters in the 245 as read with our current code:

```
=245  10$a$1oWtoIoo].oL}oPJo\d(B
```

It should look like:
```
=245  10$a중국현대문학
```

After discussion with @ahafele and @shelleydoljack at LibSys Standup, we should follow the current Symphony workflow when using MarcEdit, files are manually processed by reading as MARC8 and then saved as UTF-8 by staff.

**Comment by ahafele** [comment]
@jermnelson sample file looks good. Could you run this large file for review?  https://drive.google.com/file/d/1FOMN3A9NzByGFcyh8BIXlE25kWzr-bMl/view?usp=share_link
And is your strategy documented anywhere explicitly or can we add to this ticket (for future questions that I anticipate)?

**Comment by edsu** [comment]
I don't know if this is relevant, but up until v5 pymarc would read in MARC-8 encoded records and convert to Unicode. If you write those records back out again they got serialized as UTF-8 without updating the leader. The rationale for this was that the conversion behavior is what people putting their data into other things (databases, JSON, etc) would want. But I think over time this has led to a situation where there are records that contain UTF-8 which have not had their leader position 9 updated appropriately. This behavior changed in pymarc v5 so that position 9 in the leader is updated to 'a' when writing the data out as MARC again.
