### ISSUE TITLE
figure out authentication and authorization for users of libsys-airflow, including its vendor management app [was: Support Single Sign-On (SSO, SAML)]

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/libsys-airflow#5]
Follow suggestions in [article](https://www.manishpoddar.com/post/how-to-implement-aws-single-sign-on-sso-on-airflow) to support SSO for Stanford users.

**Comment by jgreben** [comment]
These might offer some guidance: 
https://www.manishpoddar.com/post/how-to-implement-aws-single-sign-on-sso-on-airflow
http://flask-appbuilder.readthedocs.io/en/latest/security.html

**Comment by jmartin-sul** [comment]
This might require some iteration and interaction with UIT.

Jeremy says Josh may have done some work on this last year, but not sure how far we got with actually wiring up to Airflow.

It's possible that the particular implementation of SAML support in Airflow will not play well with UIT, and we should expect turnaround time to be a bit slow if we're requesting stuff from them.

**Comment by justinlittman** [comment]
Can you say more about what the requirements are? Is an Airflow user supposed to be automatically created for a Stanford user? Or is any authenticated Stanford user supposed to be an anonymous user?

**Comment by jmartin-sul** [comment]
After much discussion and reading last week and early this week, as well as some testing in my local dev instance of libsys-airflow, we've settled on the following basic plan:
* Users of libsys-airflow who have to do things with Airflow itself, like triggering DAGs or administrating settings, will have an account created in the Airflow instance, and will log in via the Airflow login page (user accounts will be managed by the default Airflow login system, with user account info stored in its DB).
* Users of the vendor management app who do not have to do things with Airflow itself will be added to a vendor management webauth workgroup.  Since Airflow plugins (like our vendor app) allow anonymous access by default, we'll refrain from adding auth restrictions for the app in Airflow, and will instead control access to the vendor management app paths using Stanford's webauth system, allowing only people who have webauthed and who belong to the right Shibboleth workgroup to reach those paths (this is similar to what we did for KSR's Linkurious instance, though in that case we were carving out anonymous access to allow public view of visualization widgets, and restricting access via workgroup to everything else).

**Comment by jmartin-sul** [comment]
We decided not to implement the SAML integration because it seemed unnecessary, and unlike our usual SSO approach for internally developed apps, e.g. H2 and Argo.  For H2 and Argo, instead of a full-on integration with Stanford's web auth system, we get the user's sunet ID and workgroup info in a header from the Apache proxy (getting access to this info requires some coordination with UIT for each new app, iirc).  This is then used to set the `REMOTE_USER` env var for the application server process handling the request, and the app then reads that env var.  See e.g. Argo and H2 puppet configs.  This is handled by the `devise-remote-user` gem in our Rails apps, but Flask App Builder, which is used to implement (and provide extensibility for) Airflow's authN mechanism, has similar functionality (including, afaict from a cursory read of the docs, the expectation that the info will be in an env var instead of a request header).

Since we decided that the vendor app
* simply needs to restrict access to the appropriate users
* doesn't need to know specifically which sunets are performing an action as long as it belongs to an authorized user
* doesn't need the granularity of limiting authorization of certain specific actions to only a subset of people authorized to use the vendor app

It was decided that we wouldn't bother setting up `REMOTE_USER` or workgroup info passthrough, and that we'd just gate people as authorized or not for the app, per the above comment.  If we end up needing more granular authorization or audit logging, we can revisit that decision.

One tricky thing if we did revisit that:  all of our prod experience with `REMOTE_USER` passthrough is with Rails apps that use Passenger, where the sunet (and in the case of Argo, workgroup info) is passed through in an env var as mentioned at the beginning of this comment.  Additionally, in those cases Passenger is running directly on the VM from which Apache is proxying the requests.  In the case of libsys-airflow, there's a somewhat different stack with an extra layer of indirection, in that the app is running inside of a Docker container managed by Docker Compose.  We did try to spin up an experimental Dockerized version of H2 that did similarly for a Rails app, but I'm not sure whether we actually got the sunet info passthrough working there (its Puppet configs look like the other more standard H2 and Argo Puppet configs, which surprised me given the extra indirection, see h2-docker-qa config in the puppet repo).

The workgroup  based vendor app access restriction has been in place for a couple weeks, and seems to be working, so closing this ticket now that the explanation has been written up.

**Comment by jmartin-sul** [comment]
brain dump of links i found useful as of may 2023:
* https://airflow.apache.org/docs/apache-airflow/2.6.0/administration-and-deployment/security/webserver.html
* https://airflow.apache.org/docs/apache-airflow-providers/core-extensions/auth-backends.html
* https://airflow.apache.org/docs/apache-airflow/2.6.0/administration-and-deployment/security/access-control.html
* https://airflow-apache.readthedocs.io/en/latest/security.html#rbac-ui-security
* https://flask-appbuilder.readthedocs.io/en/latest/security.html#supported-authentication-types
* https://developer.squareup.com/blog/secure-apache-airflow-using-customer-security-manager/ (have only skimmed, but gives an example of `REMOTE_USER` authN)
* https://github.com/sul-dlss/puppet/blob/production/hieradata/node/argo-stage-a.stanford.edu.eyaml

Based on some discussion I saw online, it was unclear to me whether the blog post linked in the second comment applied to Airflow >= 2.x with Flask Appbuilder and RBAC for the authN mechanism.
