### ISSUE TITLE
Vendor interface links disabled when assigned_in_folio is true

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/libsys-airflow#592]
https://github.com/sul-dlss/libsys-airflow/blob/main/libsys_airflow/plugins/vendor_app/templates/vendors/vendor.html#L77

This disabled being able to view or edit the interface when `assigned_in_folio` is true.

**Comment by lwrubel** [comment]
For vendor interfaces that are no longer assigned_in_folio, I'm restoring the link to the vendor interface page from the list on the vendor page. When a user goes to that page, I'm assuming we want to hide actions such as "Process Now" and "File Upload"? Using those would not work (or do something unexpected in FOLIO?) since the interface is not connected to an org in FOLIO anymore.

**Comment by aaron-collier** [comment]
"Process Now" for sure - since we won't be able to get credentials for FTP. "File Upload" should be safe as it processes a manual file with params from our plugin config, not from FOLIO.
